//==========================================================
// Author: Jingang Han
// DATE : 2024-11-12
//==========================================================

#include <cmath>
#include <algorithm>
// #include <random>
// #include <limits>
// #include <algorithm>

#include "module_rdmft/optimizer/parameterize_ONs/ebi_constraint.h"
#include "module_rdmft/optimizer/optimizer_tools.h"
#include "module_parameter/parameter.h"
#include "module_base/parallel_common.h"

#include "module_rdmft/rdmft_tools.h" // temp

namespace rdmft
{

EBI::EBI()
{

}


EBI::~EBI()
{

}


void EBI::init(const int nk_total, const int nkstot_full, const std::vector<double> wk_in)
{
    rdmft::PARAM_ONs::init(nk_total, nkstot_full, wk_in);

    this->random_inital = PARAM.inp.random_occ_num;
    this->solve_mu_thr = PARAM.inp.solve_mu_thr;
    this->tot_nelec_thr = PARAM.inp.tot_nelec_thr;
    
    // this->solve_mu_thr = 1e-10;
    // this->tot_nelec_thr = 1e-10;
    mu.resize(PARAM.inp.nspin);
    this->dmu_dx.resize(PARAM.inp.nspin, std::vector<double>(nk_nospin*nbands, 0.0));
    // docc_num_dx.resize(PARAM.inp.nspin);


}


void EBI::get_inital_guess(std::vector<double>& x_pass, const ModuleBase::matrix* occ_number_in)
{

    // When the initial occupation numbers is too small, the gradient dE_dx provided by erf is close to 0 at small occupation numbers
    // making it difficult for small occupation numbers to change, and the optimization may falls into the local minimum! 
    // so we use init_min_num instead of PARAM.inp.min_occ_num here
    const double init_min_num = 1e-4;

    // use random numbers to generate initial values
    if(occ_number_in == nullptr)
    {
        for(int is=0; is<PARAM.inp.nspin; ++is)
        {
            std::vector<double> random_num(nk_nospin*nbands, 0.0);
            rdmft::random_descend(random_num, 1.0);
            int M = rdmft::smallest_loc_big_value(this->nk_nospin,
                                                    PARAM.inp.nbands,
                                                    this->sys_nelec_spin[is],
                                                    random_num,
                                                    this->num_symm_k.data()+is*this->nk_nospin);
            rdmft::printMatrix_pointer(nk_nospin, PARAM.inp.nbands, random_num.data(), "random_num used in EBI", 10);

            // to avoid the low bands with large-k points getting too small values ​
            // ​and the high bands with small-k points getting too large values
            // we fill the bands with descending occ_number first
            for(int ik=0; ik<nk_nospin; ++ik)
            {
                for(int ib=0; ib<nbands; ++ib)
                {
                    if( ib*nk_nospin + ik < M )
                    {
                        if( random_num[ib*nk_nospin + ik] > (std::erf(2.0) + 1.0)/2.0 ) 
                        {
                            this->x[is][ik*nbands+ib] = 2.0;
                        }
                        else
                        {
                            this->x[is][ik*nbands+ib] = erf_inv_own( random_num[ib*nk_nospin + ik] * 2.0 - 1.0 );
                        }
                    }
                    else
                    {
                        this->x[is][ik*nbands+ib] = -2.0;
                    }

                    x_pass[ is*(nk_nospin*nbands) + ik*nbands + ib ] = this->x[is][ik*nbands+ib];
                }
            }

            // // the random numbers generated by different processes may be different
            Parallel_Common::bcast_double(this->x[is].data(), nk_nospin*nbands);
        }
        
        rdmft::printMatrix_pointer(nk_nospin, PARAM.inp.nbands, this->x[0].data(), "random inital var_x", 10);
        this->solving_mu();
        rdmft::printMatrix_pointer(nk_nospin, PARAM.inp.nbands, this->occ_number[0].data(), "random inital occ_number", 10);
    }
    // use the externally passed occ_number_in as the initial value
    else
    {
        // distinguishing up and down spin, 0 < occNum < 1
        ModuleBase::matrix num_temp( *occ_number_in );
        // if( PARAM.inp.nspin == 1 ) { num_temp *= 0.5; }

        // give an initial guess for mu, 0.0 or other value
        std::fill(mu.begin(), mu.end(), 0.01);

        // std::cout << "\n******\n" << "erf_inv_own(1.0 - 1e-12) = " << erf_inv_own(1.0 - 1e-12) << "\n******\n" << std::endl;
        // std::cout << "\n******\n" << "erf_inv_own(0.0 + 1e-6) = " << erf_inv_own(0.0 + 1e-6) << "\n******\n\n" << std::endl;
        // std::cout << "\n******\n" << "erf_inv_own(1.0 - 1e-16) = " << erf_inv_own(1.0 - 1e-16) << "\n******\n\n" << std::endl;
        // std::cout << "\n******\n" << "erf( 10 ) = " << std::erf( 10 ) << "\n******\n" << std::endl;
        // std::cout << "\n******\n" << "erf( -10 ) = " << std::erf( -10 ) << "\n******\n" << std::endl;
        // std::cout << "\n******\n" << "erf( -9 ) = " << std::erf( -9 ) << "\n******\n" << std::endl;

        // std::cout << "\n******\n" << "check: \n\n";
        // std::cout << "erf( erf_inv_own(0.9999) ) = " << std::erf( erf_inv_own(0.9999) ) << ", diff: " << std::erf( erf_inv_own(0.9999) ) - 0.9999 << std::endl;
        // std::cout << "erf( erf_inv_own(0.8999) ) = " << std::erf( erf_inv_own(0.8999) ) << ", diff: " << std::erf( erf_inv_own(0.8999) ) - 0.8999 << std::endl;
        // std::cout << "erf( erf_inv_own(0.7999) ) = " << std::erf( erf_inv_own(0.7999) ) << ", diff: " << std::erf( erf_inv_own(0.7999) ) - 0.7999 << std::endl;

        for(int is=0; is<PARAM.inp.nspin; ++is)
        {
            for(int ik=0; ik<nk_nospin; ++ik)
            {
                for(int ib=0; ib<PARAM.inp.nbands; ++ib)
                {
                    double num = num_temp( is*nk_nospin + ik, ib );

                    // find the correct and finite x to ensure that erf( x + mu[is] ) = 1.0 or 0.0
                    // if( std::abs(num - 1.0) < 1e-16 )
                    // {   
                    //     // min_occ_num = 1e-16, this->x[is][ik*nbands + ib] = 5.8;
                    //     num_temp( is*nk_nospin + ik, ib ) = 1.0 - 1e-16;
                    // }
                    // else if( std::abs(num - 0.0) < 1e-16 )
                    // {
                    //     // min_occ_num = 1e-16, this->x[is][ik*nbands + ib] = -5.8;
                    //     num_temp( is*nk_nospin + ik, ib ) = 0.0 + 1e-16;
                    // }
                    if( std::abs(num - 1.0) < init_min_num )
                    {   
                        // min_occ_num = 1e-16, this->x[is][ik*nbands + ib] = 5.8;
                        num_temp( is*nk_nospin + ik, ib ) = 1.0 - init_min_num;
                    }
                    else if( std::abs(num - 0.0) < init_min_num )
                    {
                        // min_occ_num = 1e-16, this->x[is][ik*nbands + ib] = -5.8;
                        num_temp( is*nk_nospin + ik, ib ) = init_min_num;
                    }

                    this->x[is][ik*nbands + ib] = erf_inv_own( 2 * num_temp( is*nk_nospin + ik, ib ) - 1 ) - this->mu[is];
                    this->occ_number[is][ik*nbands + ib] = num_temp( is*nk_nospin + ik, ib );
                    x_pass[ is*(nk_nospin*nbands) + ik*nbands + ib ] = this->x[is][ik*nbands+ib];    
                }
            }

            // !!!!!!!!!
            // // the random numbers generated by different processes may be different
            Parallel_Common::bcast_double(this->x[is].data(), nk_nospin*nbands);

        }

        // !!!!!!!!!!!!!
        // Parallel_Common::bcast_double(x_pass.data(), nk_nospin*nbands*PARAM.inp.nspin);

        // the strictness of the above method for the conservation of occupation number depends on the precision of own_erf_inv() (mu can be given arbitrarily)
        // after obtaining the appropriate x, solving_mu() can be used to make a small move of mu
        // and the strictness of the conservation of occupation number is consistent with that in solving_mu()
        this->solving_mu();

        // for(int ik=0; ik<num_temp.nr; ++ik)
        // {
        //     for(int ib=0; ib<num_temp.nc; ++ib)
        //     {
        //         if( ik < num_temp.nr/PARAM.inp.nspin )
        //         {
        //             x[0][ik*nbands + ib] = erf_inv_own( 2 * num_temp(ik, ib) - 1 ) - mu[0];
        //             occ_number[0][ik*nbands + ib] = num_temp(ik, ib);
        //             x_pass[ ik*nbands + ib ] = this->x[0][ik*nbands+ib];
        //         }
        //         else
        //         {
        //             x[PARAM.inp.nspin-1][ik*nbands + ib] = erf_inv_own( 2 * num_temp(ik, ib) - 1 ) - mu[PARAM.inp.nspin-1];
        //             occ_number[PARAM.inp.nspin-1][ik*nbands + ib] = num_temp(ik, ib);
        //             x_pass[ (PARAM.inp.nspin-1)*(nk_nospin*nbands) + ik*nbands + ib ] = this->x[PARAM.inp.nspin-1][ik*nbands+ib];
        //         }
        //     }
        // }
        rdmft::printMatrix_pointer(num_temp.nr, num_temp.nc, occ_number_in->c, "occ_number_from_ks", 10);
        rdmft::printMatrix_pointer(num_temp.nr, num_temp.nc, this->occ_number[0].data(), "occ_number after modification, is=0", 10);
        rdmft::printMatrix_pointer(num_temp.nr, num_temp.nc, this->x[0].data(), "var_x from ks_occ_num", 10);
    }


    // When the initial occupation numbers is too small, the gradient dE_dx provided by erf is close to 0 at small occupation numbers
    // making it difficult for small occupation numbers to change, and the optimization may falls into the local minimum! 
    // so we use init_min_num instead of PARAM.inp.min_occ_num here
    // const double init_min_num = 1e-4;
    this->check_occ_num(x_pass, init_min_num);

    // // // std::cout << "\n******\n" << "start_guess: ebi, 1.0" << "\n******\n" << std::endl;
    // this->convert_x2vec(this->x, x_pass);
}



void EBI::update_x_occ_num(std::vector<double>& x_in)
{
    // std::cout << "\n" << "Enter ebi.update_x_occ_num()" << "\n" << std::endl;
    // update member variable x from external x_in
    for(int is=0; is<PARAM.inp.nspin; ++is)
    {
        for(int ik=0; ik<nk_nospin; ++ik)
        {
            for(int ib=0; ib<nbands; ++ib)
            {
                this->x[is][ik*nbands+ib] = x_in[ is*(nk_nospin*nbands) + ik*nbands +ib ];
            }
        }
    }

    // std::cout << "\n" << "before solving_mu()" << "\n" << std::endl;
    // rdmft::printMatrix_pointer(nk_nospin*PARAM.inp.nspin, nbands, x_in.data(), "trial_x", 10);

    // get the new mu and occ_number
    this->solving_mu();
    // return this->get_occ_number();

    this->check_occ_num(x_in, PARAM.inp.min_occ_num);

    // rdmft::printMatrix_pointer(nk_nospin, nbands, this->occ_number[0].data(), "spin=1, occ_number", 5);

    // rdmft::printMatrix_pointer(nk_nospin*PARAM.inp.nspin, nbands, x_in.data(), "trial_x", 10);
}


void EBI::check_occ_num(std::vector<double>& x_pass, const double min_num)
{
    for(int is=0; is<PARAM.inp.nspin; ++is)
    {
        for(int ik=0; ik<nk_nospin; ++ik)
        {
            int num_min = 0;
            for(int ib=0; ib<PARAM.inp.nbands; ++ib)
            {
                double num = this->occ_number[is][ik*this->nbands + ib];

                if( num < min_num )
                {
                    // min_occ_num = 1e-16, this->x[is][ik*nbands + ib] = -5.8;
                    this->occ_number[is][ik*this->nbands + ib] = min_num;
                    this->x[is][ik*nbands + ib] = erf_inv_own( 2 * min_num - 1 ) - this->mu[is];
                    ++num_min;
                }
            }

            // reduce the larger occupation number, speed up the solution of the new mu 
            // and make the final minimum occupation number close to min_occ_num
            if( num_min != 0 )
            {
                for(int ib2=0; ib2<PARAM.inp.nbands; ++ib2)
                {
                    double& temp_occ = this->occ_number[is][ik*this->nbands + ib2];
                    if( temp_occ > 0.01 )
                    {
                        temp_occ -= num_min * min_num;
                        this->x[is][ik*nbands + ib2] = erf_inv_own( 2 * temp_occ - 1 ) - this->mu[is];
                        break;
                    }

                    if( ib2 == PARAM.inp.nbands - 1 )
                    {
                        std::cout << "\n******\n" << "Warning: None of the k-points has an occupation number greater than 0.01" << "\n******\n" << std::endl;
                    }
                }
            }

        }

        // !!!!!!!!!
        // the return value of the erf_inv_own() function may have machine errors
        // resulting in different results for different processes
        Parallel_Common::bcast_double(this->x[is].data(), nk_nospin*nbands);

    }
    // !!!!!!!!!!!!!
    // Parallel_Common::bcast_double(x_pass.data(), nk_nospin*nbands*PARAM.inp.nspin);

    // the strictness of the above method for the conservation of occupation number depends on the precision of own_erf_inv() (mu can be given arbitrarily)
    // after obtaining the appropriate x, solving_mu() can be used to make a small move of mu
    // and the strictness of the conservation of occupation number is consistent with that in solving_mu()
    this->solving_mu();

    this->convert_x2vec(this->x, x_pass);

}


void EBI::get_dE_dx(const std::vector<double>& dE_docc_num, std::vector<double>& dE_dx)
{
    const int N = nk_nospin*nbands;
    // const double factor =  PARAM.inp.nspin==1 ? 2.0 : 1.0;
    // const double factor =  PARAM.inp.nspin==1 ? 0.5 : 1.0;
    // when spin degenerate, occ_num is also spin-sensitive, because its maximum value is 1 instead of 2
    const double factor = 1.0;
    std::vector< std::vector<double> > dE_deta(PARAM.inp.nspin, std::vector<double>(N, factor));

    for(int is=0; is<PARAM.inp.nspin; ++is)
    {
        // convert format. consider spin up and spin down separately
        for(int j=0; j<N; ++j) { dE_deta[is][j] *= dE_docc_num[is*N + j]; }

        // std::vector<double> dmu_dx(N, 0.0);
        std::vector<double> docc_num_dx(N * N, 0.0);

        this->cal_dmu_dx(this->dmu_dx[is], is);
        this->cal_docc_num_dx(this->dmu_dx[is], docc_num_dx, is);

        // rdmft::dgemm_lapack( docc_num_dx.data(), dE_deta[is].data(), (dE_dx.data() + is*N), N, 1, N );
        rdmft::dgemm_lapack( docc_num_dx.data(), dE_deta[is].data(), (dE_dx.data() + is*N), N, 1, N );
    }
}


void EBI::get_d2E_dx2(const std::vector<double>& dE_docc_num, std::vector<double>& d2E_dx2)
{
    const int N = nk_nospin*nbands;
    const double factor = 1.0;
    std::vector< std::vector<double> > dE_deta(PARAM.inp.nspin, std::vector<double>(N, factor));

    for(int is=0; is<PARAM.inp.nspin; ++is)
    {
        // convert format. consider spin up and spin down separately
        for(int j=0; j<N; ++j) { dE_deta[is][j] *= dE_docc_num[is*N + j]; }

        std::vector<double> d2mu_dx2(N, 0.0);
        std::vector<double> d2occ_num_dx2(N * N, 0.0);

        this->cal_d2mu_dx2(d2mu_dx2, is);
        this->cal_d2occ_num_dx2(d2mu_dx2, d2occ_num_dx2, is);

        rdmft::dgemm_lapack( d2occ_num_dx2.data(), dE_deta[is].data(), (d2E_dx2.data() + is*N), N, 1, N );
    }
}


void EBI::solving_mu()
{
    // std::cout << "\n" << "Enter solving_mu()" << "\n" << std::endl;
    for(int is=0; is<PARAM.inp.nspin; ++is)
    {
        // this->mu[is] = 0.0; // Is it possible to consider using the last result of mu instead of 0.0 as the initial value?
        std::vector<double> f_der(2, 1.0);
        double occ_num_error = 1.0;

        double high = 0.0;
        double low = 0.0;

        // while( f_der[0] > this->solve_mu_thr )
        // while( std::abs(f_der[0]) > this->solve_mu_thr || std::abs(occ_num_error) > this->tot_nelec_thr )
        this->solve_mu_times = 0;
        while( std::abs(occ_num_error) > this->tot_nelec_thr )
        {
            ++this->solve_mu_times;
            if( solve_mu_times > 300 )
            {
                std::cout << "\nThe number of times to solve mu using the Newton's method is too many: " << solve_mu_times << "\n" << std::endl;
                break;
            }

            // std::cout << "\n******\nsolve_mu_times: " << this->solve_mu_times << "\nis: " << is << std::endl;

            f_der = this->cal_f_der(this->mu[is], is);
            double f1_divided_f2 = std::abs( f_der[0]/f_der[1] );

            if( this->solve_mu_times > 0 ) // 50
            {
                // std::cout << "mu: " << this->mu[is] << ", f_der1: " << f_der[0] << ", f_der2: " << f_der[1] << ", f1_divided_f2: " << f1_divided_f2 << ", occ_num_error: " 
                //             << std::scientific << std::setprecision(10) << occ_num_error << "\n******" << std::endl << std::defaultfloat;
            }

            double sign = 0.0;
            if( f_der[0]>0 )
            {
                sign = 1.0;
                high = this->mu[is];
            }
            else if( f_der[0]<0 )
            {
                sign = -1.0;
                low = this->mu[is];
            }

            if( f1_divided_f2 > 1.0 )
            {
                this->mu[is] -= sign;
            }
            else
            {
                this->mu[is] -= sign * f1_divided_f2;
            }

            if( std::abs(f_der[0]) < 1e-8 )
            {
                // std::cout << "\n" << "before cal_occ_num()" << "\n" << std::endl;
                occ_num_error = this->cal_occ_num(is) - this->sys_nelec_spin[is];

                // determine whether it converges to a local minimum
                if( std::abs(occ_num_error) > this->tot_nelec_thr )
                {
                    std::cout << "******\n" << "local minimum mu: " << this->mu[is] << ", occ_num_error: " << occ_num_error << "\n******" << std::endl;

                    if( std::abs(occ_num_error) >= 0.5 && f1_divided_f2 < 0.5 )
                    {
                        double step = (occ_num_error > 0) ? 1.0 : -1.0;
                        this->mu[is] -= step;
                    }
                    else
                    {
                        // use the step length and direction of the previous step to calculate one more step
                        // this->mu[is] -= sign * f1_divided_f2;
                        
                        // do the calculation again
                        continue;
                    }

                }
            }
        }

        // for monotone problems, the bisection method can definitely be solved numerically
        // The error function is extremely sensitive to the parameter mu
        // so it is necessary to provide an initial value through the Newton's method
        // otherwise the binary search will be extremely slow in extreme cases
        if( std::abs(occ_num_error) > this->tot_nelec_thr )
        {
            this->mu[is] = high;
            double error_hi = this->cal_occ_num(is) - this->sys_nelec_spin[is];
            this->mu[is] = low;
            double error_lo = this->cal_occ_num(is) - this->sys_nelec_spin[is];

            // if the Newton's method does not provide a good initial value
            // find high_mu and low_mu
            if( std::abs(occ_num_error) > 1.0 || error_hi*error_lo > 0)
            {
                std::cout << "\n" << "the Newton's method does not provide a good initial value" << "\n" << std::endl;
                double sign = occ_num_error > 0 ? 1.0: -1.0;
                double mu_old = 0.0;
                while( 1 )
                {
                    this->mu[is] -= sign;
                    occ_num_error = this->cal_occ_num(is) - this->sys_nelec_spin[is];

                    if( occ_num_error * sign < 0 )
                    {
                        if(sign > 0)
                        {
                            high = mu_old;
                            low = this->mu[is];
                        }
                        else
                        {
                            low = mu_old;
                            high = this->mu[is];
                        }
                        break;
                    }

                    mu_old = this->mu[is];
                }
            }

            // binary search
            while( std::abs(occ_num_error) > this->tot_nelec_thr )
            {
                // temp
                ++this->solve_mu_times;
                if( this->solve_mu_times > 500 )
                {
                    std::cout << "\n" << "solve_mu_times is too big: " << this->solve_mu_times << "\n" << std::endl;
                    std::cout << "\n" << "electron number is not conserved !!!!!!!!!!! " << "\n" << std::endl;
                    assert(this->solve_mu_times <= 500);
                    break;
                }

                this->mu[is] = (high +low) / 2.0;
                occ_num_error = this->cal_occ_num(is) - this->sys_nelec_spin[is];

                std::cout << "\n******\n" << "in binary search: \n" << "is: " << is << ", times: " << this->solve_mu_times << ", mu: " << this->mu[is] 
                            << ", occ_num_error: " << occ_num_error << "\n******" << std::endl;
                
                if( occ_num_error >= 0 )
                {
                    high = this->mu[is];
                }
                else
                {
                    low = this->mu[is];
                }
            }


        }

        // std::cout << "******\n" << "solving_mu, mu[" << is << "]: " << this->mu[is] << "\n" << std::endl;
        double trial_occ_num = this->cal_occ_num(is);
        // std::cout << "spin: " << is <<", total_trial_occ_num: " <<  trial_occ_num  << "\n******" << std::endl;
    }

    //test
    // ModuleBase::matrix print_occ( this->get_occ_number() );
    // rdmft::printMatrix_pointer(print_occ.nr, print_occ.nc, print_occ.c, "occ_number_after_ebi", 10);
}

// ModuleBase::matrix EBI::get_occ_number()
// {
//     ModuleBase::matrix occ_num_pass(nk_nospin*PARAM.inp.nspin, nbands);

//     for(int ik=0; ik<occ_num_pass.nr; ++ik)
//     {
//         for(int ib=0; ib<occ_num_pass.nc; ++ib)
//         {
//             if( ik < occ_num_pass.nr/PARAM.inp.nspin )
//             {
//                 occ_num_pass(ik, ib) = this->occ_number[0][ik*nbands + ib];
//             }
//             else
//             {
//                 occ_num_pass(ik, ib) = this->occ_number[PARAM.inp.nspin-1][ik*nbands + ib];
//             }
//         }
//     }

//     // if(PARAM.inp.nspin == 1) occ_num_pass *= 2;

//     return occ_num_pass;
// }


// std::vector< std::vector<double> > EBI::cal_occ_num()
// {
//     std::vector< std::vector<double> > sum(PARAM.inp.nspin, std::vector<double>(3, 0.0));
//     for(int is=0; is<PARAM.inp.nspin; ++is)
//     {
//         for(int i=0; i<this->x[is].size(); ++i)
//         {
//             this->occ_number[is][i] = ( std::erf(this->x[is][i] + this->mu[is]) + 1.0 )/2.0;

//             sum[is][0] += this->occ_number[is][i];
//             sum[is][1] += erf_der1(this->x[is][i] + this->mu[is]);
//             sum[is][2] += erf_der2(this->x[is][i] + this->mu[is]);
//         }
//     }
//     return sum;
// }

double EBI::cal_occ_num(int is)
{
    double tot_occ_num = 0.0;
    // for(int i=0; i<this->x[is].size(); ++i)
    // {
    //     this->occ_number[is][i] = ( std::erf(this->x[is][i] + this->mu[is]) + 1.0 )/2.0;
    //     occ_num_now += this->occ_number[is][i];
    // }

    for(int ik=0; ik<nk_nospin; ++ik)
    {
        for(int ib=0; ib<PARAM.inp.nbands; ++ib)
        {
            
            this->occ_number[is][ik*nbands + ib] = ( std::erf(this->x[is][ik*nbands + ib] + this->mu[is]) + 1.0 )/2.0;
            tot_occ_num += this->occ_number[is][ik*nbands + ib] * this->num_symm_k[is*this->nk_nospin + ik];
        }
    }

    return tot_occ_num;
}

// void EBI::convert_x2vec(std::vector<double>& vec_x)
// {
//     for(int is=0; is<PARAM.inp.nspin; ++is)
//     {
//         for(int ik=0; ik<this->nk_nospin; ++ik)
//         {
//             for(int ib=0; ib<PARAM.inp.nbands; ++ib)
//             {
//                 vec_x[ is*(this->nk_nospin*nbands) + ik*nbands + ib ] = this->x[is][ik*nbands+ib];
//             }
//         }
//     }
// }


std::vector<double> EBI::cal_f_der(double mu_in, int is)
{
    std::vector<double> f_der(2, 0.0);

    // std::vector<double> sum = this->cal_sum(mu_in, is);
    std::vector<double> sum(3, 0.0);
    // for(int i=0; i<this->x[is].size(); ++i)
    // {
    //     sum[0] += ( std::erf(this->x[is][i] + mu_in) + 1.0 )/2.0;
    //     sum[1] += erf_der1(this->x[is][i] + mu_in);
    //     sum[2] += erf_der2(this->x[is][i] + mu_in);
    // }

    for(int ik=0; ik<nk_nospin; ++ik)
    {
        for(int ib=0; ib<PARAM.inp.nbands; ++ib)
        {
            sum[0] += ( std::erf(this->x[is][ik*nbands + ib] + mu_in) + 1.0 ) * 0.5 * this->num_symm_k[is*this->nk_nospin + ik];
            sum[1] += erf_der1(this->x[is][ik*nbands + ib] + mu_in) * this->num_symm_k[is*this->nk_nospin + ik];
            sum[2] += erf_der2(this->x[is][ik*nbands + ib] + mu_in) * this->num_symm_k[is*this->nk_nospin + ik];
        }
    }

    if( this->solve_mu_times > 0 ) // 50
    {
        // std::cout << "\nsum[0]: " << sum[0] << ", sum[1]: " << sum[1] << ", sum[2]: " << sum[2] << std::endl;
    }

    f_der[0] = ( sum[0] - this->sys_nelec_spin[is] ) * sum[1];
    f_der[1] = 0.5*std::pow(sum[1], 2) + ( sum[0] - this->sys_nelec_spin[is] ) * sum[2];

    return f_der;
}


// std::vector<double> EBI::cal_sum(double mu_in, int is)
// {
//     std::vector<double> sum(3, 0.0);
//     for(int i=0; i<this->x[is].size(); ++i)
//     {
//         sum[0] += ( std::erf(this->x[is][i] + mu_in) + 1.0 )/2.0;
//         sum[1] += erf_der1(this->x[is][i] + mu_in);
//         sum[2] += erf_der2(this->x[is][i] + mu_in);
//     }
//     return sum;
// }


void EBI::cal_dmu_dx(std::vector<double>& dmu_dx_in, int is)
{
    double sum_der1 = 0.0;
    for(int i=0; i<this->x[is].size(); ++i) { sum_der1 += erf_der1(this->x[is][i] + this->mu[is]); }

    for(int j=0; j<dmu_dx_in.size(); ++j) { dmu_dx_in[j] = - erf_der1(this->x[is][j] + this->mu[is]) / sum_der1; }
}


void EBI::cal_d2mu_dx2(std::vector<double>& d2mu_dx2, int is)
{
    std::vector<double> sum_der(2, 0.0);
    for(int i=0; i<this->x[is].size(); ++i)
    {
        sum_der[0] += erf_der1(this->x[is][i] + this->mu[is]);
        sum_der[1] += erf_der2(this->x[is][i] + this->mu[is]) * std::pow(this->dmu_dx[is][i], 2);
    }

    for(int j=0; j<d2mu_dx2.size(); ++j)
    {
        d2mu_dx2[j] = - ( erf_der2(this->x[is][j] + this->mu[is]) * (1 + 2*this->dmu_dx[is][j]) + sum_der[1] ) / sum_der[0];
    }
}

void EBI::cal_docc_num_dx(const std::vector<double>& dmu_dx_in, std::vector<double>& docc_num_dx, int is)
{
    const int N = nk_nospin*nbands;
    for(int i=0; i<N; ++i)
    {
        for(int j=0; j<N; ++j)
        {
            if( i==j )
            {
                docc_num_dx[i*N+j] = 0.5 * erf_der1(this->x[is][i] + this->mu[is]) * (1 + dmu_dx_in[i]);
            }
            else
            {
                docc_num_dx[i*N+j] = 0.5 * erf_der1(this->x[is][i] + this->mu[is]) * dmu_dx_in[j];
            }
        }
    }
}


void EBI::cal_d2occ_num_dx2(const std::vector<double>& d2mu_dx2, std::vector<double>& d2occ_num_dx2, int is)
{
    const int N = nk_nospin*nbands;
    for(int i=0; i<N; ++i)
    {
        for(int j=0; j<N; ++j)
        {
            if( i==j )
            {
                d2occ_num_dx2[i*N+j] = 0.5 * erf_der2(this->x[is][i] + this->mu[is]) * std::pow((1 + this->dmu_dx[is][i]), 2)
                                        + 0.5 * erf_der1(this->x[is][i] + this->mu[is]) * d2mu_dx2[i];
            }
            else
            {
                d2occ_num_dx2[i*N+j] = 0.5 * erf_der2(this->x[is][i] + this->mu[is]) * std::pow(this->dmu_dx[is][j], 2)
                                        + 0.5 * erf_der1(this->x[is][i] + this->mu[is]) * d2mu_dx2[j];
            }
        }
    }
}






}

