//==========================================================
// Author: Jingang Han
// DATE : 2025-07-10
//==========================================================


#include <cmath>
#include <algorithm>

#include "module_rdmft/optimizer/parameterize_ONs/softmax.h"
#include "module_rdmft/optimizer/optimizer_tools.h"
#include "module_parameter/parameter.h"
#include "module_base/parallel_common.h"


namespace rdmft
{


SOFTMAX::SOFTMAX()
{

}


SOFTMAX::~SOFTMAX()
{

}


void SOFTMAX::get_inital_guess(std::vector<double>& x_pass, const ModuleBase::matrix* occ_number_in)
{
    std::fill(x_pass.begin(), x_pass.end(), 0.0);

    // use random numbers to generate initial values
    if(occ_number_in == nullptr)
    {
        for(int is=0; is<PARAM.inp.nspin; ++is)
        {
            const int N = nk_nospin*nbands;
            std::vector<double> random_num(N, 0.0);
            rdmft::random_descend(random_num, 3.0);
            // the random numbers generated by different processes may be different
            Parallel_Common::bcast_double(random_num.data(), N);

            for(int ik=0; ik<nk_nospin; ++ik)
            {
                for(int ib=0; ib<nbands; ++ib)
                {
                    x_pass[ is*(nk_nospin*nbands) + ik*nbands + ib ] = random_num[ib*nk_nospin + ik] - random_num[0];
                }
            }

            // for(int j=0; j<N; ++j)
            // {
            //     x_pass[is*N +j] = random_num[j] - random_num[0];
            // }

            rdmft::printMatrix_pointer(nk_nospin, PARAM.inp.nbands, random_num.data(), "random_num used in SOFTMAX", 10);
        }
    }
    // use the externally passed occ_number_in as the initial value
    else
    {
        ModuleBase::matrix num_temp( *occ_number_in );
        for(int is=0; is<PARAM.inp.nspin; ++is)
        {
            // const double max_x = std::log( num_temp(is*nk_nospin, 0) / this->sys_nelec_spin[is] );
            // the number of particles with different spins is conserved separately
            double max_occ_num = *std::max_element(num_temp.c + is*nk_nospin*nbands, num_temp.c + (is+1)*nk_nospin*nbands);
            const double max_x = std::log( max_occ_num / this->sys_nelec_spin[is] );

            for(int ik=0; ik<nk_nospin; ++ik)
            {
                for(int ib=0; ib<PARAM.inp.nbands; ++ib)
                {
                    // according to the existing occ_number, reverse solve x
                    double num = num_temp( is*nk_nospin + ik, ib );
                    x_pass[ is*(nk_nospin*nbands) + ik*nbands + ib ] = std::log( num / this->sys_nelec_spin[is] ) - max_x;
                }
            }
        }

        // will there be errors in the reverse solution? Execute for safety
        Parallel_Common::bcast_double(x_pass.data(), PARAM.inp.nspin*nk_nospin*nbands);
    }

    // When the initial occupation numbers is too small, the gradient dE_dx provided by softmax is close to 0 at small occupation numbers
    // making it difficult for small occupation numbers to change, and the optimization may falls into the local minimum! 
    // let exp(x_i)/sum = 1/C * exp(x_max)/sum, get x_i = x_max - ln(C) 
    const double ln_C = - std::log(1e4);
    for(int i=0; i<x_pass.size(); ++i)
    {
        if(x_pass[i] < ln_C)
        {
            x_pass[i] = ln_C;
        }
    }

    // get the initial occ_number and check
    this->update_x_occ_num(x_pass);

    rdmft::printMatrix_pointer(nk_nospin, PARAM.inp.nbands, this->x[0].data(), "inital var_x", 10);
    rdmft::printMatrix_pointer(nk_nospin, PARAM.inp.nbands, this->occ_number[0].data(), "inital occ_number", 10);

}


void SOFTMAX::update_x_occ_num(std::vector<double>& x_in)
{
    this->modify_x = false;
    // update member variable x from external x_in
    std::vector<double> max_x_in(PARAM.inp.nspin, 0.0);
    for(int is=0; is<PARAM.inp.nspin; ++is)
    {
        max_x_in[is] = *std::max_element(x_in.begin() + is*(nk_nospin*nbands), x_in.begin() + (is+1)*(nk_nospin*nbands));
        for(int ik=0; ik<nk_nospin; ++ik)
        {
            for(int ib=0; ib<nbands; ++ib)
            {
                // preventing exp() overflow
                // the {x} in the softmax class differs from the actual {x_in} by a constant
                this->x[is][ik*nbands+ib] = x_in[ is*(nk_nospin*nbands) + ik*nbands +ib ] - max_x_in[is];
            }
        }

        double sum_exp = this->cal_occ_num(is);

        this->check_occ_num(is, sum_exp);
    }

    if( this->modify_x )
    {
        std::vector< std::vector<double> > x_temp = this->x;
        for(int is=0; is<PARAM.inp.nspin; ++is)
        {
            for(int j=0; j<x_temp[is].size(); ++j)
            {
                x_temp[is][j] += max_x_in[is];
            }
        }
        this->convert_x2vec(x_temp, x_in);
    }


    // temp, to test
    for(int is=0; is<PARAM.inp.nspin; ++is)
    {
        double tot_nelec = 0.0;
        for(int ik=0; ik<nk_nospin; ++ik)
        {
            for(int ib=0; ib<PARAM.inp.nbands; ++ib)
            {
                tot_nelec += this->occ_number[is][ik*nbands + ib] * this->num_symm_k[is*this->nk_nospin + ik];
            }
        }

        double tot_nelec_error = tot_nelec - this->sys_nelec_spin[is];
        std::cout << "******\nis: " << is << ", tot_nelec_error: " << tot_nelec_error << "\n******" << std::endl;
        rdmft::printMatrix_pointer(nk_nospin, PARAM.inp.nbands, this->occ_number[is].data(), "occ_number by softmax", 10);
    }

}


void SOFTMAX::get_dE_dx(const std::vector<double>& dE_docc_num, std::vector<double>& dE_dx)
{
    
    const int N = nk_nospin*nbands;
    
    // when spin degenerate, occ_num is also spin-sensitive, because its maximum value is 1 instead of 2
    const double factor = 1.0;
    std::vector< std::vector<double> > dE_deta(PARAM.inp.nspin, std::vector<double>(N, factor));

    for(int is=0; is<PARAM.inp.nspin; ++is)
    {
        // convert format. consider spin up and spin down separately
        for(int j=0; j<N; ++j) { dE_deta[is][j] *= dE_docc_num[is*N + j]; }

        std::vector<double> docc_num_dx(N * N, 0.0);
        this->cal_docc_num_dx(docc_num_dx, is);

        // rdmft::Tgemm_lapack( docc_num_dx.data(), dE_deta[is].data(), (dE_dx.data() + is*N), N, 1, N );
        rdmft::Tgemm_lapack( docc_num_dx.data(), dE_deta[is].data(), (dE_dx.data() + is*N), N, 1, N );
        std::cout << "\nis: " << is << std::endl;
        rdmft::printMatrix_pointer(nk_nospin, PARAM.inp.nbands, (dE_dx.data() + is*N), "dE_dx", 10);
    }

}


double SOFTMAX::cal_occ_num(const int is)
{
    // softmax
    double sum = 0.0;
    for(int ik=0; ik<nk_nospin; ++ik)
    {
        for(int ib=0; ib<PARAM.inp.nbands; ++ib)
        {
            this->occ_number[is][ik*nbands + ib] = std::exp(this->x[is][ik*nbands + ib]);
            sum += this->occ_number[is][ik*nbands + ib] * this->num_symm_k[is*this->nk_nospin + ik];
        }
    }

    for(int i=0; i<this->occ_number[is].size(); ++i)
    {
        this->occ_number[is][i] *= this->sys_nelec_spin[is]/sum;
    }

    return sum;
}


void SOFTMAX::cal_docc_num_dx(std::vector<double>& docc_num_dx, int is)
{
    const int N = nk_nospin*nbands;
    for(int i=0; i<N; ++i)
    {
        for(int j=0; j<N; ++j)
        {
            if( i==j )
            {
                docc_num_dx[i*N+j] = this->occ_number[is][i] * (1.0 - this->occ_number[is][i]);
            }
            else
            {
                docc_num_dx[i*N+j] = - this->occ_number[is][i] * this->occ_number[is][j];
            }
            docc_num_dx[i*N+j] *= this->sys_nelec_spin[is];
        }
    }
}


// when occ_num=1 is not considered, it will be added later
void SOFTMAX::check_occ_num(const int is, const double sum_exp)
{
    // according to the minimum value of the ONs, the minimum value of x is approximately
    bool occur_min = false;
    double min_x = std::log(sum_exp * PARAM.inp.min_occ_num / this->sys_nelec_spin[is]);
    for(int ik=0; ik<nk_nospin; ++ik)
    {
        for(int ib=0; ib<PARAM.inp.nbands; ++ib)
        {
            double num = this->occ_number[is][ik*this->nbands + ib];
            if( num < PARAM.inp.min_occ_num )
            {
                this->x[is][ik*nbands + ib] = min_x;
                occur_min = true;

                this->modify_x = true;
            }
        }
    }

    Parallel_Common::bcast_double(this->x[is].data(), nk_nospin*nbands);
    if( occur_min )
    {
        this->cal_occ_num(is);
    }
}








}









